# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160126_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
